/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_BACK.h"
#include "PWM_BACK_aliases.h"
#include "PWM_FRONT.h"
#include "PWM_FRONT_aliases.h"
#include "I2C_0.h"
#include "I2C_0_I2C.h"
#include "I2C_0_PINS.h"
#include "I2C_0_I2C_PVT.h"
#include "I2C_0_PVT.h"
#include "I2C_0_BOOT.h"
#include "Bootloader_0.h"
#include "Bootloader_0_PVT.h"
#include "PWM_BACK_C.h"
#include "Clock_1.h"
#include "DIR_FRONT_LEFT.h"
#include "DIR_FRONT_LEFT_aliases.h"
#include "DIR_FRONT_RIGHT.h"
#include "DIR_FRONT_RIGHT_aliases.h"
#include "DIR_BACK_LEFT.h"
#include "DIR_BACK_LEFT_aliases.h"
#include "DIR_BACK_RIGHT.h"
#include "DIR_BACK_RIGHT_aliases.h"
#include "ENABLE_MOTORS.h"
#include "ENABLE_MOTORS_aliases.h"
#include "PWM_FRONT_C.h"
#include "LED_0.h"
#include "LED_0_aliases.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "LED_3.h"
#include "LED_3_aliases.h"
#include "BUTTON_TILT_EN.h"
#include "BUTTON_TILT_EN_aliases.h"
#include "BUTTON_MOTOR_EN.h"
#include "BUTTON_MOTOR_EN_aliases.h"
#include "BUTTON_DIR_UP.h"
#include "BUTTON_DIR_UP_aliases.h"
#include "BUTTON_DIR_DOWN.h"
#include "BUTTON_DIR_DOWN_aliases.h"
#include "I2C_0_SCBCLK.h"
#include "I2C_0_sda.h"
#include "I2C_0_sda_aliases.h"
#include "I2C_0_scl.h"
#include "I2C_0_scl_aliases.h"
#include "I2C_0_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

